// <auto-generated />
using System;
using DenialsCommandCenter.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DenialsCommandCenter.Api.Data.Migrations
{
    [DbContext(typeof(DenialsDbContext))]
    [Migration("20261005130646_AddDenialAnalysis")]
    partial class AddDenialAnalysis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DenialsCommandCenter.Api.Data.AppealDraftRow", b =>
                {
                    b.Property<string>("FactsHash")
                        .HasColumnType("text");

                    b.Property<string>("AiConfidence")
                        .HasColumnType("text");

                    b.Property<string>("AiOwningTeam")
                        .HasColumnType("text");

                    b.Property<string>("AiPreventable")
                        .HasColumnType("text");

                    b.Property<string>("AiRootCause")
                        .HasColumnType("text");

                    b.Property<string>("CitationsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ClaimId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LetterTemplate")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusReason")
                        .HasColumnType("text");

                    b.HasKey("FactsHash");

                    b.HasIndex("ClaimId");

                    b.ToTable("AppealDrafts");
                });

            modelBuilder.Entity("DenialsCommandCenter.Api.Data.ClaimRow", b =>
                {
                    b.Property<string>("ClaimId")
                        .HasColumnType("text");

                    b.Property<string>("CoderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("DateOfService")
                        .HasColumnType("date");

                    b.Property<string>("Facility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("PatientDob")
                        .HasColumnType("date");

                    b.Property<string>("PatientFirst")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientLast")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlaceOfService")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PrebillReviewed")
                        .HasColumnType("boolean");

                    b.Property<string>("RenderingNpi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RenderingProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("SubmittedDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalCharge")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("ClaimId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("DenialsCommandCenter.Api.Data.ClaimStateRow", b =>
                {
                    b.Property<string>("ClaimId")
                        .HasColumnType("text");

                    b.Property<decimal>("BilledCharge")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateOnly?>("DenialDate")
                        .HasColumnType("date");

                    b.Property<string>("DenialLinesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("DeniedAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("EventCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("LastRemitDate")
                        .HasColumnType("date");

                    b.Property<decimal>("NetPaid")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("PossibleOverpayment")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WasRecouped")
                        .HasColumnType("boolean");

                    b.HasKey("ClaimId");

                    b.ToTable("ClaimStates");
                });

            modelBuilder.Entity("DenialsCommandCenter.Api.Data.DenialAnalysisRow", b =>
                {
                    b.Property<string>("ClaimId")
                        .HasColumnType("text");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CitationsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConfidenceReason")
                        .HasColumnType("text");

                    b.Property<int?>("DaysToDeadline")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("Deadline")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DenialDate")
                        .HasColumnType("date");

                    b.Property<decimal>("DeniedAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("ExpectedValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("NextAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwningTeam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Preventable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PriorityScore")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("ReasonCodes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RootCause")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClaimId");

                    b.ToTable("DenialAnalyses");
                });

            modelBuilder.Entity("DenialsCommandCenter.Api.Data.IngestionIssueRow", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("ClaimId")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.HasIndex("ClaimId");

                    b.ToTable("IngestionIssues");
                });

            modelBuilder.Entity("DenialsCommandCenter.Api.Data.IngestionRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Difference")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("Events")
                        .HasColumnType("integer");

                    b.Property<string>("InputHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Issues")
                        .HasColumnType("integer");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReportJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("IngestionRuns");
                });

            modelBuilder.Entity("DenialsCommandCenter.Api.Data.RemitEventRow", b =>
                {
                    b.Property<string>("EventKey")
                        .HasColumnType("text");

                    b.Property<decimal>("Charge")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("ClaimId")
                        .HasColumnType("text");

                    b.Property<int>("FileOrder")
                        .HasColumnType("integer");

                    b.Property<decimal>("Paid")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("PayerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RawClaimRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("SourceFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TraceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EventKey");

                    b.HasIndex("ClaimId");

                    b.ToTable("RemitEvents");
                });

            modelBuilder.Entity("DenialsCommandCenter.Api.Data.SourceFileRow", b =>
                {
                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<int>("ClaimPayments")
                        .HasColumnType("integer");

                    b.Property<int>("DuplicateEvents")
                        .HasColumnType("integer");

                    b.Property<int>("FileOrder")
                        .HasColumnType("integer");

                    b.Property<string>("InterchangeControlNumber")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("InterchangeDate")
                        .HasColumnType("date");

                    b.Property<int>("NewEvents")
                        .HasColumnType("integer");

                    b.Property<decimal>("NewPaymentTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PaymentTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FileName");

                    b.ToTable("SourceFiles");
                });

            modelBuilder.Entity("DenialsCommandCenter.Api.Data.WorklogEntryRow", b =>
                {
                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("ClaimId")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("LoggedDate")
                        .HasColumnType("date");

                    b.Property<string>("LoggedDateCandidates")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .HasColumnType("text");

                    b.Property<string>("Patient")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payer")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SuspiciousText")
                        .HasColumnType("boolean");

                    b.HasKey("RowNumber");

                    b.HasIndex("ClaimId");

                    b.ToTable("WorklogEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
